import type { Metadata } from "next";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { cn } from "@/lib/utils";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import "@mantine/core/styles.css";
import { Inter } from "next/font/google";
import Head from "./Head";
import { ThemeProvider } from "@/components/theme-provider"

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cn(
            'antialiased min-h-screen transition !bg-[#080809] text-neutral-50 aeonikFont',
            font.className,
        )}>

            <head>
                <ColorSchemeScript />
                <Head />
            </head>

            <body>
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
                
                    <MantineProvider>
                        <Header />
                        
                        {children}
                
                        <Footer />
                    </MantineProvider>
                
                    </ThemeProvider>
            </body>
        </html>
    );
};